<?php

declare( strict_types=1 );

namespace WebMultipliers\ArtifactCanvas;

/**
 * Dedicated artifact-authoring capabilities.
 *
 * Replaces the old unfiltered_html gate on the post type with a proper
 * capability set (edit_wm_artifacts, publish_wm_artifacts, …) generated by
 * capability_type = wm_artifact + map_meta_cap. Administrators receive the
 * full set on activation; other roles can be granted capabilities via any
 * role editor or WP-CLI.
 *
 * Trust boundary: holding these capabilities does NOT imply unfiltered_html.
 * Authors without unfiltered_html still get wp_kses_post applied to artifact
 * HTML on save (Security::sanitize_on_save), and cannot save the analytics
 * snippet field (ClientTracking auth_callback).
 */
class Capabilities {

	/** All primitive capabilities the wm_artifact post type generates. */
	public const ALL = array(
		'edit_wm_artifact',
		'read_wm_artifact',
		'delete_wm_artifact',
		'edit_wm_artifacts',
		'edit_others_wm_artifacts',
		'delete_wm_artifacts',
		'delete_others_wm_artifacts',
		'delete_published_wm_artifacts',
		'delete_private_wm_artifacts',
		'publish_wm_artifacts',
		'read_private_wm_artifacts',
		'edit_published_wm_artifacts',
		'edit_private_wm_artifacts',
	);

	/** Option storing the schema version of the last capability grant. */
	public const GRANTED_OPTION = 'wmac_caps_version';

	public function register_hooks(): void {
		add_action( 'admin_init', array( $this, 'maybe_upgrade' ) );
	}

	/**
	 * One-shot grant for installs that were activated before the dedicated
	 * capability set existed (the activation hook does not re-fire on update).
	 */
	public function maybe_upgrade(): void {
		if ( get_option( self::GRANTED_OPTION ) === '1' ) {
			return;
		}
		self::grant_to_administrator();
		update_option( self::GRANTED_OPTION, '1' );
	}

	/** Grants the full capability set to administrators. Called on activation. */
	public static function grant_to_administrator(): void {
		$role = get_role( 'administrator' );
		if ( ! $role ) {
			return;
		}

		foreach ( self::ALL as $cap ) {
			$role->add_cap( $cap );
		}
	}

	/** Removes the capability set from every role. Called on uninstall. */
	public static function remove_from_all_roles(): void {
		$roles = wp_roles();

		foreach ( array_keys( $roles->roles ) as $role_name ) {
			$role = get_role( $role_name );
			if ( ! $role ) {
				continue;
			}
			foreach ( self::ALL as $cap ) {
				$role->remove_cap( $cap );
			}
		}
	}
}
